### ISSUE TITLE
Bug - email template markdown not rendering 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#119]
Hey @christianmorfordwaitessw 

Any idea why the Markdown for **email-template** is not rendering in the good example here: https://www.ssw.com.au/rules/dones-do-you-use-email-for-tasks-only-not-communication ? 
The syntax seems alright

1. Please investigate and fix

<img width="1008" alt="Screen Shot 2021-03-03 at 10 33 42 AM" src="https://user-images.githubusercontent.com/12601228/109854486-f3b2d500-7c0b-11eb-9725-8029a1caee0f.png">

[AB#60214](https://ssw.visualstudio.com/ecd18a76-dd97-4cb9-bbb4-d2edfaa0a78c/_workitems/edit/60214)

**Comment by christianmorfordwaitessw** [comment]
Hi @tiagov8,

> 1. Please investigate and fix

**Done** - This has already been resolved due to a whitespace fix.
See https://www.ssw.com.au/rules/dones-do-you-use-email-for-tasks-only-not-communication
![image](https://user-images.githubusercontent.com/56522256/120143859-478d8400-c224-11eb-9e2a-5ba642699888.png)
**Figure: Email template rendering correctly again**

-Christian
