### ISSUE TITLE
Bug - Content change PRs failing

### ISSUE THREAD

**Issue by UlyssesMaclaren** [SSWConsulting/SSW.Rules.Content#121]
Automated tests failing on all of my PRs... even if all i did was remove a space

example 1: https://github.com/SSWConsulting/SSW.Rules.Content/pull/120
example 2: https://github.com/SSWConsulting/SSW.Rules.Content/pull/112

**Comment by tiagov8** [comment]
See how only Uly's content changes are failing:
<img width="544" alt="Screen Shot 2021-03-03 at 3 22 34 PM" src="https://user-images.githubusercontent.com/12601228/109886964-cb3fd080-7c35-11eb-8133-f945288aea3e.png">

**Comment by JackLeerson** [comment]
Hi @tiagov8, @UlyssesMaclaren 

This is now fixed. 

The problem was that the GitHub action we were using had a bug that read multiline commit body messages directly, which meant that we were trying to create an environment variable with the name of a newline symbol. 

I have forked the creator's repository, and wrapped the input in a string, which seems to have fixed the issue. We are currently using my forked repository in the workflow, but I have submitted a pull request to the owner to merge. We can then switch back to the original.
