### ISSUE TITLE
What's the best way to move images/documents from a folder to another

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#5292]
Cc: @adamcogan @tombui99 

Hi @bradystroud 
  
This rule URL was changed from
   https://ssw.com.au/rules/best-free-resources-for-angular
to
   https://ssw.com.au/rules/the-best-learning-resources-for-angular

Since then, the PDF file is giving a 404 😕 ([caught by CodeAuditor](https://codeauditor.com/build/a012dfc3-bdda-4a45-eba5-03b34ea15c9a))
The image still works, but it should be in its rule folder...

1. What is the best way to move these 2 files to the new folder? 
2. Can we add these steps to the wiki?

<img width="1290" alt="Screenshot 2023-04-04 at 12 35 57 PM" src="https://user-images.githubusercontent.com/12601228/229844780-fe208681-a782-46ea-8bda-548e1e3870c2.png">

**Comment by bradystroud** [comment]
Hey @tiagov8,

> 1. What is the best way to move these 2 files to the new folder?

I plan to make a video on this topic, because their is no easy way to do it.
You need to either delete and re-upload the images in the new folder, or clone the repo and move the files locally (using File Explorer or Finder)

To go back and fix all the files that are in the wrong folder, we can write a simple script. See https://github.com/SSWConsulting/SSW.Rules/issues/940

**Comment by tiagov8** [comment]
I guess it's better to wait for the script :)
