### ISSUE TITLE
Broken links found by CodeAuditor

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.Content#636]
cc: @adamcogan, @pierssinclairssw 
Hi @tiagov8,

As per my conversation with Adam and Piers, I should have used a GitHub Issue to give you this task so this is a copy of the email I already sent.
 
1. Please fix these broken links found by CodeAuditor
https://codeauditor.com/build/d1940f08-dc43-449b-fd8b-4db933ff1927
 
Thanks,
 
-Brady

**Comment by tiagov8** [comment]
Hi @bradystroud ,

as per our conversation, I've fixed several links yesterday (see closed PRs: https://github.com/SSWConsulting/SSW.Rules.Content/pulls?q=is%3Apr+is%3Aclosed)

The latest report https://codeauditor.com/build/f4d4172f-2f97-437f-96d1-ba5045b4f998 only showed 2 errors:

- The first is fixed by https://github.com/SSWConsulting/SSW.Rules.Content/pull/649
- The second seems like a false positive, as all the images were fixed by you, and are working fine on https://www.ssw.com.au/rules/all-the-things-you-can-use-qr-code-for

Maybe we should get a newer report to see if we get 0 this time ;)

**Comment by bradystroud** [comment]
Hi @tiagov8,

A more recent CodeAuditor scan has found 43 broken links!

1. Please fix these links
https://codeauditor.com/build/624d6ed1-4430-4a26-4a1a-7acb5253d87c

Thanks,

-Brady

**Comment by tiagov8** [comment]
Hi @bradystroud 

done - fixed the links, except for this one:
<img width="1248" alt="Screen Shot 2021-04-27 at 5 14 43 PM" src="https://user-images.githubusercontent.com/12601228/116327967-be92b100-a77c-11eb-95ec-ecdfe05b1035.png">

Not broken - see https://github.com/SSWConsulting/SSW.CodeAuditor/issues/215 for more info

**Comment by tiagov8** [comment]
Since we had multiple CA reports after this, I'm closing it
